- hosts: localhost
  gather_facts: no

  vars:
    docker_id: whiter018
    docker_key: "{{ lookup('env', 'DOCKER_KEY')}}"
    container_name: goorm_myweb
    image_name: "{{ docker_id }}/goorm_myweb"


  tasks:
  - block:
    - name: Image Build with WAR
      docker_image:
        build:
          path: .
          rm: yes
        name: "{{ image_name }}"
        push: yes
        source: build

